### ISSUE TITLE
爆炸摧毀月台閘門導致遊戲崩潰回檔

### ISSUE THREAD

**Issue by ZiYueCommentary** [jonafanho/Minecraft-Transit-Railway#124]
當我把TNT放在月台閘門旁邊並引爆之後，遊戲停止了運行並且存檔滾回到了上一次自動保存的版本

**Comment by jonafanho** [comment]
您好，有沒有 crash report?

**Comment by ZiYueCommentary** [comment]
> 您好，有沒有 crash report?

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mtr.block.IBlock.onBreakCreative(IBlock.java:88)
	at mtr.block.BlockDirectionalDoubleBlockBase.method_9576(BlockDirectionalDoubleBlockBase.java:49)
	at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:66)
	at mtr.block.BlockPSDTop.method_9586(BlockPSDTop.java:74)
	at net.minecraft.class_1927.method_8350(class_1927.java:284)
	at net.minecraft.class_3218.method_8454(class_3218.java:1032)
	at net.minecraft.class_1937.method_8437(class_1937.java:573)
	at net.minecraft.class_1541.method_6971(class_1541.java:100)
	at net.minecraft.class_1541.method_5773(class_1541.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_3218$$Lambda$6036/1642844106.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5717/432006769.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mtr.block.IBlock.onBreakCreative(IBlock.java:88)
	at mtr.block.BlockDirectionalDoubleBlockBase.method_9576(BlockDirectionalDoubleBlockBase.java:49)
	at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:66)
	at mtr.block.BlockPSDTop.method_9586(BlockPSDTop.java:74)
	at net.minecraft.class_1927.method_8350(class_1927.java:284)
	at net.minecraft.class_3218.method_8454(class_3218.java:1032)
	at net.minecraft.class_1937.method_8437(class_1937.java:573)
	at net.minecraft.class_1541.method_6971(class_1541.java:100)
	at net.minecraft.class_1541.method_5773(class_1541.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_3218$$Lambda$6036/1642844106.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:tnt (net.minecraft.class_1541)
	Entity ID: 41
	Entity Name: 被激活的TNT
	Entity's Exact location: 232.60, 26.00, -36.67
	Entity's Block location: World: (232,26,-37), Chunk: (at 8,1,11 in 14,-3; contains blocks 224,0,-48 to 239,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

[更完整的崩溃报告](https://ziyuecommentary.lanzoui.com/iiVhutv5q5g)

**Comment by linuxkettle** [comment]
You tried to blow up platform screen doors?

**Comment by ZiYueCommentary** [comment]
> You tried to blow up platform screen doors?

这是我在偶然发现的错误，如果有人借此恶意针对有mtr模组的服务器会发生什么

**Comment by jonafanho** [comment]
@ZiYueCommentary Does this still happen in the latest version?

**Comment by ZiYueCommentary** [comment]
> @ZiYueCommentary Does this still happen in the latest version?

这个bug在beta-8的fabric版中依旧存在（仅站台屏蔽门Platform Screen Doors）

**Comment by DreamUniverse843** [comment]
This bug still exist in beta-9.
Crash-report:https://paste.ubuntu.com/p/ft98yM4GmZ/

**Comment by kettle-7** [comment]
Canonical website O.o

**Comment by DreamUniverse843** [comment]
> @jonafanho 我在我自己的開發環境裡找到了一個疑似跟問題有關的異常 Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.player.PlayerEntity.isCreative()" because "player" is null 這可能跟IBlock內onBreakCreative方法裡檢測玩家是否為創造有關

Maybe that's it,because my crash-report pointed that:

**Comment by ZiYueCommentary** [comment]
> > @jonafanho 我在我自己的開發環境裡找到了一個疑似跟問題有關的異常 Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.player.PlayerEntity.isCreative()" because "player" is null 這可能跟IBlock內onBreakCreative方法裡檢測玩家是否為創造有關
> 
> Maybe that's it,because my crash-report pointed that: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7337()" because "player" is null

我刚才删除了那里面关于检测玩家是否为创造的部分
没有任何问题！摧毁屏蔽门不再导致崩溃
不确定是否会不会影响其他方块的破坏

**Comment by DreamUniverse843** [comment]
但是我这个 net.minecraft.class_1657.method_7337() 不确定是什么...

**Comment by DreamUniverse843** [comment]
`---- Minecraft Crash Report ----
// There are four lights!

Time: 2022/2/1 上午12:17
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7337()" because "player" is null
	at mtr.block.IBlock.onBreakCreative(IBlock.java:79)
	at mtr.block.BlockPSDAPGDoorBase.method_9576(BlockPSDAPGDoorBase.java:54)
	at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:72)
	at mtr.block.BlockPSDTop.method_9586(BlockPSDTop.java:80)
	at net.minecraft.class_1927.method_8350(class_1927.java:291)
	at net.minecraft.class_3218.method_8454(class_3218.java:969)
	at net.minecraft.class_1937.method_8437(class_1937.java:507)
	at net.minecraft.class_1541.method_6971(class_1541.java:100)
	at net.minecraft.class_1541.method_5773(class_1541.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mtr.block.IBlock.onBreakCreative(IBlock.java:79)
	at mtr.block.BlockPSDAPGDoorBase.method_9576(BlockPSDAPGDoorBase.java:54)
	at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:72)
	at mtr.block.BlockPSDTop.method_9586(BlockPSDTop.java:80)
	at net.minecraft.class_1927.method_8350(class_1927.java:291)
	at net.minecraft.class_3218.method_8454(class_3218.java:969)
	at net.minecraft.class_1937.method_8437(class_1937.java:507)
	at net.minecraft.class_1541.method_6971(class_1541.java:100)
	at net.minecraft.class_1541.method_5773(class_1541.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: minecraft:tnt (net.minecraft.class_1541)
	Entity ID: 587
	Entity Name: Primed TNT
	Entity's Exact location: 7.89, 21.00, 14.72
	Entity's Block location: World: (7,21,14), Section: (at 7,5,14 in 0,1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: -0.14, 0.00, -0.20
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 3 total; [class_3222['DreamUniverse'/63, l='ServerLevel[testrail]', x=22.92, y=29.15, z=11.12], class_3222['wangkelbw'/155, l='ServerLevel[testrail]', x=14.21, y=35.39, z=33.96], class_3222['XiaoYuan'/172, l='ServerLevel[testrail]', x=774.27, y=89.12, z=-1081.52]]
	Chunk stats: 4991
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,32), Section: (at 0,0,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 50104102 game time, 154873 day time
	Level name: testrail
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2120317784 bytes (2022 MiB) / 4137680896 bytes (3946 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Microsoft 基本显示适配器
	Graphics card #0 vendor: (标准显示卡类型) (0x1013)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: DriverVersion=10.0.14393.0
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 12881.48
	Virtual memory used (MB): 7026.50
	Swap memory total (MB): 4690.00
	Swap memory used (MB): 181.54
	JVM Flags: 1 total; -Xmx4G
	Fabric Mods: 
		chiselsandbits: Chisels & Bits 1.2.60
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		mtr: Minecraft Transit Railway 1.18-3.0.0-beta-9-unofficial-2
		worldedit: WorldEdit 7.2.8+6008-1246d61
	Server Running: true
	Player Count: 3 / 20; [class_3222['DreamUniverse'/63, l='ServerLevel[testrail]', x=22.92, y=29.15, z=11.12], class_3222['wangkelbw'/155, l='ServerLevel[testrail]', x=14.21, y=35.39, z=33.96], class_3222['XiaoYuan'/172, l='ServerLevel[testrail]', x=774.27, y=89.12, z=-1081.52]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by ZiYueCommentary** [comment]
> 

Fabric模组里默认自带混淆（可能？）
我在开发环境里使用的是没有混淆的开发版本，所以能找到对应问题的位置

**Comment by DreamUniverse843** [comment]
也许吧，一会我去编译一份新的试试看。

**Comment by DreamUniverse843** [comment]
> > > @jonafanho 我在我自己的開發環境裡找到了一個疑似跟問題有關的異常 Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.player.PlayerEntity.isCreative()" because "player" is null 這可能跟IBlock內onBreakCreative方法裡檢測玩家是否為創造有關
> > 
> > 
> > Maybe that's it,because my crash-report pointed that: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7337()" because "player" is null
> 
> 我刚才删除了那里面关于检测玩家是否为创造的部分 没有任何问题！摧毁屏蔽门不再导致崩溃 不确定是否会不会影响其他方块的破坏

```
common\src\main\java\mtr\block\BlockDirectionalDoubleBlockBase.java:54
                        IBlock.onBreakCreative(world, player, pos.below());
                              ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockPSDAPGDoorBase.java:54
                IBlock.onBreakCreative(world, player, offsetPos);
                      ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockEscalatorSide.java:45
                IBlock.onBreakCreative(world, player, offsetPos);
                      ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockEscalatorStep.java:39
                        IBlock.onBreakCreative(world, player, pos.relative(IBlock.getSideDirection(state)));
                              ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockPIDSBase.java:70
                        IBlock.onBreakCreative(world, player, pos.relative(facing));
                              ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockRailwaySign.java:92
                        IBlock.onBreakCreative(world, player, checkPos);
                              ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockStationNameTallBase.java:69
                                IBlock.onBreakCreative(world, player, pos.below());
                                      ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
common\src\main\java\mtr\block\BlockStationNameTallBase.java:72
                                IBlock.onBreakCreative(world, player, pos.below(2));
                                      ^
  符号:   方法 onBreakCreative(Level,Player,BlockPos)
  位置: 接口 IBlock
```
应该就这些有对 onBreakCreative 的引用，一会我也挨个看一下。

**Comment by DreamUniverse843** [comment]
似乎还是不行...只删掉 player.isCreative() 还是会导致崩溃
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26164(net.minecraft.class_3494)" because "$$2" is null
	at net.minecraft.class_2248.method_9576(class_2248.java:499)
	at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:75)
	at mtr.block.BlockPSDTop.method_9586(BlockPSDTop.java:80)
	at net.minecraft.class_1927.method_8350(class_1927.java:291)
	at net.minecraft.class_3218.method_8454(class_3218.java:969)
	at net.minecraft.class_1937.method_8437(class_1937.java:507)
	at net.minecraft.class_1541.method_6971(class_1541.java:100)
	at net.minecraft.class_1541.method_5773(class_1541.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.redirect$zip000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4250)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zbn000$modifiedRunLoop(MinecraftServer.java:3356)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ZiYueCommentary** [comment]
我不太确定你是怎么修改的，看起来你用的是有混淆的版本？
可能是我使用的是旧版本，不会导致什么问题

晓宇致梦Universe ***@***.***> 于2022年2月21日周一 17:41写道：

**Comment by DreamUniverse843** [comment]
> 

我不确定我的改法对不对...
我把 onBreakCreative 方法里面的 ```&& player.isCreative()``` 删掉了重新编译的...
![image](https://user-images.githubusercontent.com/53889721/154929410-bbdd2936-306a-4f81-89d7-ac6f8c8f6358.png)

**Comment by ZiYueCommentary** [comment]
> > 
> 
> 我不确定我的改法对不对... 我把 onBreakCreative 方法里面的 `&& player.isCreative()` 删掉了重新编译的... ![image](https://user-images.githubusercontent.com/53889721/154929410-bbdd2936-306a-4f81-89d7-ac6f8c8f6358.png)

我自己是这么弄得，能不能问一下你修改的版本？

**Comment by DreamUniverse843** [comment]
beta-9

**Comment by ZiYueCommentary** [comment]
> beta-9

我的意思是，你的beta-9是刚下的吗
我修改的beta-9版本是有forge之前的

**Comment by DreamUniverse843** [comment]
是，刚下的。

**Comment by ZiYueCommentary** [comment]
> 是，刚下的。

我不太确定新版beta-9里都有什么影响结果的东西，我待会自己试试

**Comment by DreamUniverse843** [comment]
> 我不太确定新版beta-9里都有什么影响结果的东西，我待会自己试试
```at mtr.block.BlockPSDTop.method_9576(BlockPSDTop.java:75)```
应该是这个，一会我也去看看 BlockPSDTop 里有什么。
谢谢！
