### ISSUE TITLE
MTR-1.18-3.0.0-beta-8-prerelease-1 Doesn't work in 21w40a

### ISSUE THREAD

**Issue by xingxing2008** [jonafanho/Minecraft-Transit-Railway#176]
MTR-1.18-3.0.0-beta-8-prerelease-1 Doesn't work in 21w40a
support it ! I needed

**Comment by cherbert** [comment]
Don't be so rude.

**Comment by cherbert** [comment]
MTR-1.18-3.0.0-beta-8-prerelease-1 doesn't exist. And why would he support a snapshot?

**Comment by jonafanho** [comment]
It's for the 1.18 experimental snapshots, and you need a specific Fabric API version.

**Comment by xingxing2008** [comment]
lasted log
`[18:57:41] [Render thread/INFO]: Failed to find module info for D:\Game\MINECRAFT\1.18 Snapshot modded\.minecraft\versions\21w40a-Fabric 0.12.1\21w40a-Fabric 0.12.1-natives\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: 找不到映像文件中指定的资源类型。
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[intermediary-21w40a-Fabric%200.12.1.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[intermediary-21w40a-Fabric%200.12.1.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[intermediary-21w40a-Fabric%200.12.1.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [intermediary-21w40a-Fabric%200.12.1.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [intermediary-21w40a-Fabric%200.12.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [intermediary-21w40a-Fabric%200.12.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.1.jar:?]
[18:57:41] [Render thread/INFO]: Failed to find module info for D:\Game\MINECRAFT\1.18 Snapshot modded\.minecraft\versions\21w40a-Fabric 0.12.1\21w40a-Fabric 0.12.1-natives\jemalloc.dll`

**Comment by xingxing2008** [comment]
> That's a problem with Fabric talking to OpenGL and has nothing to do with this mod.

This is about this mod, because when I delete this mod, this error will not be reported. ‘
When I add this mod, the game will crash and report this error

**Comment by Ultimate-USA-YT** [comment]
> > > what is Specific Fabric api version I use Fabric Loader (0.12.1) and Fabric Api Mod (0.40.8) How do i use
> > 
> > 
> > Just Pop the MTR Mod and API into the Mods Folder
> 
> yep，but it doesn't work

I meant 1.17

**Comment by kettle-7** [comment]
Wait you're using a version that we don't support, of course there's gonna be problems! You're as likely to get that working as forge 1.12!
