### ISSUE TITLE
Fabric 1.18-pre8 crashes due to fabric api

### ISSUE THREAD

**Issue by creepinson** [jonafanho/Minecraft-Transit-Railway#227]
**Expected Behaviour**
The game should launch into the main menu.

**Actual Behaviour**
Crashes upon launching minecraft.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Use `1.18-pre8` with fabric loader `0.12.5`, fabric api `0.43.0` and MTR `1.18-3.0.0-beta-8-prerelease-1`

**Crash Report**
```
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/block/entity/BlockEntityClientSerializable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at mtr.Blocks.<clinit>(Blocks.java:53)
	at mtr.MTR.<clinit>(MTR.java:35)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
```

**Screenshots**

**Environment**

- Minecraft Version: 1.18-pre8

**Additional Information**

**Comment by cherbert** [comment]
@jonafanho this is why you shouldn't support snapshots.

**Comment by jonafanho** [comment]
The 1.18 versions are for the experimental snapshots. I will release the mod for 1.18 soon.
