### ISSUE TITLE
Game crashing with mod

### ISSUE THREAD

**Issue by Shadowgamer483** [jonafanho/Minecraft-Transit-Railway#230]
**Expected Behaviour**
to load my minecraft without it crashing because of mtr(this mod)

**Actual Behaviour**
I put the mod it loaded fabric mc with sodium and some other mods and it keeps crashing as soon as i take out mtr(this mod) my minecraft starts up and doesnt  crash 

**Reproduction Steps**
Steps to reproduce the behaviour:

1.put the mod in the mods foolder in .minecraft

**Crash Report**
[14:14:38] [main/INFO]: Loading for game Minecraft 1.18
[14:14:38] [ForkJoinPool-1-worker-4/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[14:14:38] [main/INFO]: Loading 80 mods:
	- adorn 3.0.0-rc.1+1.18-rc3
	- architectury 3.1.45
	- blockus 2.3.3+1.18
	- blue_endless_jankson 1.2.1 via jankson
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42
	- crowdin-translate 1.3+1.17 via mtr
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via fabric
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514 via fabric
	- fabric-biome-api-v1 6.0.1+3ac43d9514 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9514 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9514 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-containers-v0 0.1.18+d154e2c614 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d14 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9514 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957114 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a14 via fabric
	- fabric-events-interaction-v0 0.4.15+3ac43d9514 via fabric
	- fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9514 via fabric
	- fabric-item-api-v1 1.2.7+3ac43d9514 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9514 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f314 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd14 via fabric
	- fabric-language-kotlin 1.7.0+kotlin.1.6.0
	- fabric-lifecycle-events-v1 1.4.10+c15ca33514 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9514 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9514 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd14 via fabric
	- fabric-models-v0 0.3.3+3ac43d9514 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9514 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd14 via fabric
	- fabric-object-builder-api-v1 1.10.13+3ac43d9514 via fabric
	- fabric-object-builders-v0 0.7.7+3ac43d9514 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac14 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d9514 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9514 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9514 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd14 via fabric
	- fabric-rendering-data-attachment-v1 0.3.3+d154e2c614 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9514 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd14 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a14 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9514 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9514 via fabric
	- fabric-structure-api-v1 2.0.8+295197a714 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9514 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9514 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5514 via fabric
	- fabric-transfer-api-v1 1.5.4+b4f4f6cd14 via fabric
	- fabricloader 0.12.8
	- gobber2 2.5.50
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.0.0-beta.2+1.18-rc1 via adorn
	- libninepatch 1.1.0 via libgui
	- minecraft 1.18
	- mo_glass 1.5-MC1.18
	- mtr 1.18-3.0.0-beta-8-prerelease-1
	- org_jetbrains_kotlin_kotlin-reflect 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- paintings 1.0.0.6
	- pugh_lib 1.2.11 via gobber2
	- pugh_tools 1.1.13 via gobber2
	- ring_of_miner 1.3.14
	- roughlyenoughitems 7.0.342
	- sodium 0.4.0-alpha5+build.9
	- terraform-wood-api-v1 2.0.2 via blockus
[14:14:38] [main/WARN]: Mod `paintings` (1.0.0.6) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[14:14:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Daksh/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[14:14:39] [main/INFO]: Compatibility level set to JAVA_16
[14:14:39] [main/INFO]: Compatibility level set to JAVA_17
[14:14:39] [main/WARN]: Reference map 'RingOfMiner-Fabric-1.18-pre5-refmap.json' for ring_of_miner.mixins.json could not be read. If this is a development environment you can ignore this message
[14:14:39] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[14:14:40] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[14:14:42] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[14:14:42] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[14:14:42] [main/WARN]: Disabling further attempts to query Paging File.
[14:14:44] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[14:14:47] [main/INFO]: Gobber Mod Info Message: Max value of attribute.name.generic.armor is currently set to 80.0
[14:14:53] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zgh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:14:59] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:15:03] [Render thread/INFO]: Setting user: depressedshado
[14:15:15] [Render thread/INFO]: loading json file and contents for paintings.
[14:15:15] [Render thread/INFO]: Copying Over Base Template to /paintings
[14:15:15] [Render thread/INFO]: Reading out ResourcePacks to find painting related json files
[14:15:15] [Render thread/INFO]: Reading `1.17`
[14:15:15] [Render thread/WARN]: ************************************
[14:15:15] [Render thread/ERROR]: Invalid ResourcePack  1.17
[14:15:15] [Render thread/ERROR]: Provider "jar" not found
[14:15:15] [Render thread/WARN]: ************************************
[14:15:15] [Render thread/INFO]: Started Reading all json files in /painting directory
[14:15:15] [Render thread/INFO]: .\paintings\paintings.json
[14:15:16] [Render thread/INFO]: Loaded json painting abstract_blue , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting abstract_rainbow , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting abstract_red , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting abstract_sunset , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting arachnophobe , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting barn_owl , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting big_z , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting blue_bird , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting bluesclues , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting borgia , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting cane , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting cat_black , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting cat_gray , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting cat_orange , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting cat , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting colorful_squares , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting crest , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting danger_zone , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting decorative_gun , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting exit_down , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting exit_up , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting exit_left , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting exit_right , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_bat , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_chicken , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_cow , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_creeper , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_dog , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_enderman , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_pig , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_pigman , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_silverfish , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_skeleton , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_squid , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting face_zombie , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting fishes , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting flowers , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting fruits , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting ghost , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting glowlamp , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting glowstone_hourglass , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting iluvmc , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting link , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting mine_prosperity , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting no_trespassing_for_mobs , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting ocelot , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting penguin , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting pig_on_a_cliff , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting pkmn_blue , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting pkmn_red , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting pkmn_green , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting plains_hut , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting portrait_2 , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting portrait , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting prison , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting prosperity , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting rest , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting skeleton , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting sky , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting skyblock , 32 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting snake , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting snow_landscape , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting subaraki , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting synth_city , 16 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting tapistry_a , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting tapistry_b , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting tapistry_purple , 16 x 32
[14:15:16] [Render thread/INFO]: Loaded json painting torched , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting waterfall , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting whale , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting wheat_field , 32 x 16
[14:15:16] [Render thread/INFO]: Loaded json painting wolf_in_wheat , 32 x 16
[14:15:16] [Render thread/INFO]: Registered painting paintings:abstract_blue
[14:15:16] [Render thread/INFO]: Registered painting paintings:abstract_rainbow
[14:15:16] [Render thread/INFO]: Registered painting paintings:abstract_red
[14:15:16] [Render thread/INFO]: Registered painting paintings:abstract_sunset
[14:15:16] [Render thread/INFO]: Registered painting paintings:arachnophobe
[14:15:16] [Render thread/INFO]: Registered painting paintings:barn_owl
[14:15:16] [Render thread/INFO]: Registered painting paintings:big_z
[14:15:16] [Render thread/INFO]: Registered painting paintings:blue_bird
[14:15:16] [Render thread/INFO]: Registered painting paintings:bluesclues
[14:15:16] [Render thread/INFO]: Registered painting paintings:borgia
[14:15:16] [Render thread/INFO]: Registered painting paintings:cane
[14:15:16] [Render thread/INFO]: Registered painting paintings:cat_black
[14:15:16] [Render thread/INFO]: Registered painting paintings:cat_gray
[14:15:16] [Render thread/INFO]: Registered painting paintings:cat_orange
[14:15:16] [Render thread/INFO]: Registered painting paintings:cat
[14:15:16] [Render thread/INFO]: Registered painting paintings:colorful_squares
[14:15:16] [Render thread/INFO]: Registered painting paintings:crest
[14:15:16] [Render thread/INFO]: Registered painting paintings:danger_zone
[14:15:16] [Render thread/INFO]: Registered painting paintings:decorative_gun
[14:15:16] [Render thread/INFO]: Registered painting paintings:exit_down
[14:15:16] [Render thread/INFO]: Registered painting paintings:exit_up
[14:15:16] [Render thread/INFO]: Registered painting paintings:exit_left
[14:15:16] [Render thread/INFO]: Registered painting paintings:exit_right
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_bat
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_chicken
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_cow
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_creeper
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_dog
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_enderman
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_pig
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_pigman
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_silverfish
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_skeleton
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_squid
[14:15:16] [Render thread/INFO]: Registered painting paintings:face_zombie
[14:15:16] [Render thread/INFO]: Registered painting paintings:fishes
[14:15:16] [Render thread/INFO]: Registered painting paintings:flowers
[14:15:16] [Render thread/INFO]: Registered painting paintings:fruits
[14:15:16] [Render thread/INFO]: Registered painting paintings:ghost
[14:15:16] [Render thread/INFO]: Registered painting paintings:glowlamp
[14:15:16] [Render thread/INFO]: Registered painting paintings:glowstone_hourglass
[14:15:16] [Render thread/INFO]: Registered painting paintings:iluvmc
[14:15:16] [Render thread/INFO]: Registered painting paintings:link
[14:15:16] [Render thread/INFO]: Registered painting paintings:mine_prosperity
[14:15:16] [Render thread/INFO]: Registered painting paintings:no_trespassing_for_mobs
[14:15:16] [Render thread/INFO]: Registered painting paintings:ocelot
[14:15:16] [Render thread/INFO]: Registered painting paintings:penguin
[14:15:16] [Render thread/INFO]: Registered painting paintings:pig_on_a_cliff
[14:15:16] [Render thread/INFO]: Registered painting paintings:pkmn_blue
[14:15:16] [Render thread/INFO]: Registered painting paintings:pkmn_red
[14:15:16] [Render thread/INFO]: Registered painting paintings:pkmn_green
[14:15:16] [Render thread/INFO]: Registered painting paintings:plains_hut
[14:15:16] [Render thread/INFO]: Registered painting paintings:portrait_2
[14:15:16] [Render thread/INFO]: Registered painting paintings:portrait
[14:15:16] [Render thread/INFO]: Registered painting paintings:prison
[14:15:16] [Render thread/INFO]: Registered painting paintings:prosperity
[14:15:16] [Render thread/INFO]: Registered painting paintings:rest
[14:15:16] [Render thread/INFO]: Registered painting paintings:skeleton
[14:15:16] [Render thread/INFO]: Registered painting paintings:sky
[14:15:16] [Render thread/INFO]: Registered painting paintings:skyblock
[14:15:16] [Render thread/INFO]: Registered painting paintings:snake
[14:15:16] [Render thread/INFO]: Registered painting paintings:snow_landscape
[14:15:16] [Render thread/INFO]: Registered painting paintings:subaraki
[14:15:16] [Render thread/INFO]: Registered painting paintings:synth_city
[14:15:16] [Render thread/INFO]: Registered painting paintings:tapistry_a
[14:15:16] [Render thread/INFO]: Registered painting paintings:tapistry_b
[14:15:16] [Render thread/INFO]: Registered painting paintings:tapistry_purple
[14:15:16] [Render thread/INFO]: Registered painting paintings:torched
[14:15:16] [Render thread/INFO]: Registered painting paintings:waterfall
[14:15:16] [Render thread/INFO]: Registered painting paintings:whale
[14:15:16] [Render thread/INFO]: Registered painting paintings:wheat_field
[14:15:16] [Render thread/INFO]: Registered painting paintings:wolf_in_wheat
[14:15:16] [Render thread/INFO]: PughLib has loaded - v1.2.11
[14:15:16] [Render thread/INFO]: PughTools has loaded - v1.1.13
[14:15:16] [Render thread/INFO]: Config loaded.
[14:15:16] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[14:15:16] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[14:15:17] [Render thread/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[14:15:25] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[14:15:25] [Render thread/INFO]: Failed to find module info for C:\WINDOWS\SYSTEM32\UMPDC.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:205) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
[14:15:25] [Render thread/INFO]: Failed to find module info for C:\Users\Daksh\AppData\Roaming\.minecraft\bin\7670-7ca7-c131-5d8b\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:205) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
[14:15:25] [Render thread/INFO]: Failed to find module info for C:\Users\Daksh\AppData\Roaming\.minecraft\bin\7670-7ca7-c131-5d8b\glfw.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:205) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]

**Screenshots**
dont have

**Environment**

- Minecraft Version:1.18

mods
-![image_2021-12-02_141729](https://user-images.githubusercontent.com/60564162/144420430-9bb16709-0fa5-4aa8-b539-d89512ad5741.png)

**Additional Information**
no

**Comment by Ultimate-USA-YT** [comment]
This mod is NOT compatable with 1.18. Please use 1.17.1 or 1.16.5 (Stable)

**Comment by jonafanho** [comment]
That file is only for the 1.18 experimental snapshots. Please see the #previews channel on Discord for a 1.18 (release) build. https://discord.gg/PVZ2nfUaTW

**Comment by kettle-7** [comment]
We do have a custom invite link now...
