### ISSUE TITLE
too fast rendering causes bug

### ISSUE THREAD

**Issue by Entchenbrot** [jonafanho/Minecraft-Transit-Railway#264]
**Expected Behaviour**
A normal ride with a train 120km/h+

**Actual Behaviour**
Any train above 120km/h will cause a log output about being too fast resulting in the player being stuck in the air without the train existing anymore. The server doesn't crash but you have to rejoin and fast rails are not able to be used (occurs after a distance of approximatly 800 blocks traveled, depends on the speed of the track)
I get why the problem occurs, the rendering is just to slow to handle the speed, but my question is if there's a way to fix it
Also it's kinda weird that you are stuck in the air, the world around you might or might not render at some point but you're still stuck, as if you were in the train but you can't see it, it doesn't move and you can't get out. A rejoin fixes the stuckness at least

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Have a huge modpack lol (fabric)
2. Make a track over 1000 blocks with tracks which have a speed higher than 120km/h (and even the 120km/h got problematic after 3000 blocks traveled)
3. Ride the track

**Crash Report** (respectively log output from server since there is no actual crash)
[03:27:51] [Server thread/ERROR]: Entity moves too fast class_3222['entchenbrot'/99415, l='ServerWorld minecraft:overworld Whats poppin', x=-961.30, y=94.99, z=3555.30](0.18099419978761944, -0.001460973203421645, -61.63994587842217)6053188
[03:27:51] [Server thread/INFO]: [STDERR]: java.lang.Throwable
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1297.md3144b7$lambda$redirectHandleCollisions$0$7(class_1297.java:16066)
[03:27:51] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.my_util.LimitedLogger.invoke(LimitedLogger.java:28)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1297.redirect$cfd000$redirectHandleCollisions(class_1297.java:16064)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1297.method_5784(class_1297.java:623)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12063(class_3244.java:893)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828.method_12272(class_2828.java:114)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:21)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:151)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:125)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18857(class_1255.java:134)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
[03:27:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[03:27:51] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

**Environment**

- Minecraft Version: Fabric 1.17.1
- Installed Mods: many, including mods which create some heavy world gen which results in lags sometimes (so I guess the server just hates it being too fast, I mean that's what it's saying)

**Additional Information**
My question would be if there is a way for me to fix it, like playing around with some settings or if I just have to live with my trains not being able to make more than 80km/h
Or is there a plan for a version which could resolve this problem

Thanks in advance! This is one of the best mods ever and I played with it's features all day long

**Comment by HistoryButtsandCo10** [comment]
Interesting, we could talk this over in our discord server. Ngl, this is quite new, possibly this is a server-side issue. Though I am also suggesting that maybe a lack of processing power from your computer as well; anyways join your discord here. https://discord.gg/gCFEzFTX. Thanks!
