### ISSUE TITLE
Mod Not Loading Properly

### ISSUE THREAD

**Issue by JaydenChu0731** [jonafanho/Minecraft-Transit-Railway#450]
**Expected Behaviour**
The mod will load properly like any other mods. 

**Actual Behaviour**
An error screen appeared

**Reproduction Steps**

1. Install Tlauncher
2. Press the Tlauncher Mod button at the right-bottom corner
3. Create a mod-pack with version 1.19 and latest version of forge
4. Press Mod
5. Search for Transit
6. Install the Mod
7. Press the yellow button at the bottom
8. Wait for Minecraft to load 

**Crash Report**
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/8/2022 下午1:24
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23160!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:596) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mtr.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD mtr --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry
		at mtr.mappings.ForgeUtilities.registerKeyBinding(ForgeUtilities.java:30) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
		at mtr.forge.RegistryClientImpl.registerKeyBinding(RegistryClientImpl.java:44) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
		at mtr.RegistryClient.registerKeyBinding(RegistryClient.java) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
		at mtr.MTRClientLifts.init(MTRClientLifts.java:36) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
		at mtr.MTRClient.init(MTRClient.java:319) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
		at mtr.MTRForge$MTRModEventBus.onClientSetupEvent(MTRForge.java:115) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading,pl:eventbus:A}
		at mtr.__MTRModEventBus_onClientSetupEvent_FMLClientSetupEvent.invoke(.dynamic) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.1.0.jar%23157!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.1.0.jar%23156!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Administrator/AppData/Roaming/.minecraft/versions/shaderssssssssssssssss/mods/MTR-forge-1.19-3.0.1.jar
	Failure message: Minecraft Transit Railway (mtr) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry
	Mod Version: 1.19-3.0.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.ClientRegistry
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at mtr.mappings.ForgeUtilities.registerKeyBinding(ForgeUtilities.java:30) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
	at mtr.forge.RegistryClientImpl.registerKeyBinding(RegistryClientImpl.java:44) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
	at mtr.RegistryClient.registerKeyBinding(RegistryClient.java) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
	at mtr.MTRClientLifts.init(MTRClientLifts.java:36) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
	at mtr.MTRClient.init(MTRClient.java:319) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading}
	at mtr.MTRForge$MTRModEventBus.onClientSetupEvent(MTRForge.java:115) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading,pl:eventbus:A}
	at mtr.__MTRModEventBus_onClientSetupEvent_FMLClientSetupEvent.invoke(.dynamic) ~[MTR-forge-1.19-3.0.1.jar%23149!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.1.0.jar%23157!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.1.0.jar%23156!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1003685864 bytes (957 MiB) / 2516582400 bytes (2400 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics 655
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea5
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1660
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20879.91
	Virtual memory used (MB): 16380.43
	Swap memory total (MB): 4630.73
	Swap memory used (MB): 325.84
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19_HD_U_H9_pre4
	OptiFine Build: 20220724-215219
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.32+Medium.zip
	OpenGlVersion: 3.2.0 - Build 30.0.101.1660
	OpenGlRenderer: Intel(R) Iris(R) Plus Graphics 655
	OpenGlVendor: Intel
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		tl_skin_cape_forge_1.19-1.26.jar                  |TLSkinCape                    |tlskincape                    |1.26                |ENQUEUE_IM|Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-5.10.32-forge.jar                    |Architectury                  |architectury                  |5.10.32             |ENQUEUE_IM|Manifest: NOSIGNATURE
		MTR-forge-1.19-3.0.1.jar                          |Minecraft Transit Railway     |mtr                            |1.19-3.0.1          |ERROR     |Manifest: NOSIGNATURE
		MTR-LU-Addon-forge-1.19-3.0.1-1.1.jar             |MTR London Underground Addon  |londonunderground             |1.19-3.0.1-1.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 5c214f33-7d14-438f-b2c8-dce4da47f110
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/110372021/182078442-679c1e11-b2b7-4717-ab2a-fed7bda043e3.png)

**Environment**

- Minecraft Version: 1.19
- Installed Mods: tl_skin_cape, MrCrayfish's Furniture Mod, Architectury, Minecraft Transit Railway, MTR London Underground Addon

**Additional Information**
This is on tlauncher, not the official Minecraft launcher

**Comment by kettle-7** [comment]
We do not support use of TLauncher or other cracked launchers. Unfortunately you need to pay for mincefart if you want to use MTR.

**Comment by Big-Cake-jpg** [comment]
> We do not support use of TLauncher or other cracked launchers. Unfortunately you need to pay for mincefart if you want to use MTR. 

Wake up, please, you're spelling wrong.

By the way, game crashed was not related to the "Cracked Launcher". You shouldn't link these two unrelated things.

**Comment by kettle-7** [comment]
> Wake up, please, you're spelling wrong.

It's well intentional actually.

> By the way, game crashed was not related to the "Cracked Launcher".

Actually...

**Comment by Ultimate-USA-YT** [comment]
> > We do not support use of TLauncher or other cracked launchers. Unfortunately you need to pay for mincefart if you want to use MTR.
> 
> Wake up, please, you're spelling wrong.
> 
> By the way, game crashed was not related to the "Cracked Launcher". You shouldn't link these two unrelated things.
> 
> Also, TLauncher didn't provide offline authentication to players.
> 
> This image is from BakaXL User group. ![image](https://user-images.githubusercontent.com/76810494/182271969-200a0f49-e60e-43b3-961b-cb8d4926ca7e.jpeg)

Actually, it is Related, Quite a Nice System to Prevent the Mod Being Used in Pirated Minecraft Launchers.

**Comment by Big-Cake-jpg** [comment]
> Actually, it is Related, Quite a Nice System to Prevent the Mod Being Used in Pirated Minecraft Launchers.

There's no saying about "Pirate Minecraft Launchers". Third-party launcher shouldn't be the reason that lead the game to crash.

**Comment by Ultimate-USA-YT** [comment]
> > Actually, it is Related, Quite a Nice System to Prevent the Mod Being Used in Pirated Minecraft Launchers.
> 
> There's no saying about "Pirate Minecraft Launchers". Third-party launcher shouldn't be the reason that lead the game to crash.

...

**Comment by Ultimate-USA-YT** [comment]
I Meant Pirated Minecraft.

**Comment by aab8102** [comment]
用hmcl启动器啊
Try using the hmcl launcher
