### ISSUE TITLE
Mod crashes when i start mc

### ISSUE THREAD

**Issue by Jakub5209** [jonafanho/Minecraft-Transit-Railway#591]
**Expected Behaviour**
A clear and concise description of what you expected to happen. Mod work normally

**Actual Behaviour**
mc crash

**Reproduction Steps**
Steps to reproduce the behaviour:

1. turn on minecraft with the mtr + architectury = crash

**Crash Report**
---- Minecraft Crash Report ----
// Why did you do that?

Time: 28.12.2022, 11:21
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23150!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mtr.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD mtr --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry
		at mtr.mappings.ForgeUtilities.registerKeyBinding(ForgeUtilities.java:30) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
		at mtr.forge.RegistryClientImpl.registerKeyBinding(RegistryClientImpl.java:44) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
		at mtr.RegistryClient.registerKeyBinding(RegistryClient.java) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
		at mtr.MTRClientLifts.init(MTRClientLifts.java:36) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
		at mtr.MTRClient.init(MTRClient.java:319) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
		at mtr.MTRForge$MTRModEventBus.onClientSetupEvent(MTRForge.java:115) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading,pl:eventbus:A}
		at mtr.__MTRModEventBus_onClientSetupEvent_FMLClientSetupEvent.invoke(.dynamic) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.1.0.jar%23147!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.1.0.jar%23146!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/jkrzy/AppData/Roaming/.minecraft/versions/server/mods/MTR-forge-1.19-3.0.1.jar
	Failure message: Minecraft Transit Railway (mtr) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry
	Mod Version: 1.19-3.0.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.ClientRegistry
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at mtr.mappings.ForgeUtilities.registerKeyBinding(ForgeUtilities.java:30) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
	at mtr.forge.RegistryClientImpl.registerKeyBinding(RegistryClientImpl.java:44) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
	at mtr.RegistryClient.registerKeyBinding(RegistryClient.java) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
	at mtr.MTRClientLifts.init(MTRClientLifts.java:36) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
	at mtr.MTRClient.init(MTRClient.java:319) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading}
	at mtr.MTRForge$MTRModEventBus.onClientSetupEvent(MTRForge.java:115) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading,pl:eventbus:A}
	at mtr.__MTRModEventBus_onClientSetupEvent_FMLClientSetupEvent.invoke(.dynamic) ~[MTR-forge-1.19-3.0.1.jar%23144!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.1.0.jar%23147!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.1.0.jar%23146!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Screenshots**
![image](https://user-images.githubusercontent.com/84958099/209797681-aefffa25-594a-4fd5-aff3-b9e62bd165af.png)

**Environment**

- Minecraft Version: 1.19
- Installed Mods: Just mtr and architectury

**Additional Information**
Anything else you want to add? no

**Comment by saleem0915** [comment]
Are all your mods up to date?

**Comment by Jakub5209** [comment]
> Are all your mods up to date?

I think that yes

**Comment by saleem0915** [comment]
@jonafanho What do you think

**Comment by saleem0915** [comment]
Or, it may just be that MTR is incompatible with Architectury. I have seen many concerns saying Minecraft crashes when MTR and Architectury are used together.

**Comment by jonafanho** [comment]
Please make sure all your mods are up to date (Minecraft Transit Railway Forge, Architectury Forge, etc.) and check that you are using the same Minecraft version for all those mods (eg. don't mix 1.19, 1.19.2, and 1.19.3).
