### ISSUE TITLE
1.20.1 Forge服务器安装MTR无法启动 | 1.20.1 Forge server cannot start when MTR installed

### ISSUE THREAD

**Issue by littlekan233** [jonafanho/Minecraft-Transit-Railway#724]
_Tip：This issue's English text translated by DeepL._

**发生情境 | Scenario**
我正在和我的朋友开一个1.20.1 Forge核心的MTR服务器，装上此mod后开服时因为一条来自mod的报错而导致服务器崩溃
I'm running a 1.20.1 Forge core MTR server with my friend, and after installing this mod the server crashed when I started because of an error report from the mod

**错误报告 | Crash Reports**
_此报告较长，请耐心看完_
_This is a long report, so please bear with me. _
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-07-20 13:09:30
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20-46.0.1-universal.jar%23176!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.20-46.0.1-universal.jar%23176!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20-20230608.053357-srg.jar%23171!/:?] {re:classloading,pl:accesstransformer:B}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:30) ~[fmlloader-1.20-46.0.1.jar%23103!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:46) ~[arclight-forge-1.20-1.0.0-SNAPSHOT.jar:arclight-1.20-1.0.0-SNAPSHOT-0293741] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:13) ~[arclight-forge-1.20-1.0.0-SNAPSHOT.jar:arclight-1.20-1.0.0-SNAPSHOT-0293741] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) ~[arclight-forge-1.20-1.0.0-SNAPSHOT.jar%2383!/:arclight-1.20-1.0.0-SNAPSHOT-0293741] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:18) ~[arclight-forge-1.20-1.0.0-SNAPSHOT.jar%2383!/:arclight-1.20-1.0.0-SNAPSHOT-0293741] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20-46.0.1.jar%23103!/:1.0] {}
-- MOD mtr --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
		at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23169!/:?] {re:classloading}
		at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23169!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20-46.0.1.jar%23173!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.20-46.0.1.jar%23172!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/creep/桌面/minecraft1.20-server/mods/MTR-forge-1.20-3.2.2-hotfix-1.jar
	Failure message: Minecraft Transit Railway (mtr) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
	Mod Version: 1.20-3.2.2-hotfix-1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20-46.0.1.jar%23103!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2389!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23169!/:?] {re:classloading}
	at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23169!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20-46.0.1.jar%23173!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.20-46.0.1.jar%23172!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Linux (amd64) version 6.2.0-25-generic
	Java Version: 17.0.7, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1720676288 bytes (1640 MiB) / 2147483648 bytes (2048 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: MCP89 [GeForce 320M]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x08a0
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7933.70
	Virtual memory used (MB): 3005.65
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.51
	JVM Flags: 3 total; -Xms1G -Xmx8G -XX:+UseContainerSupport
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: arclightserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		arclight-forge-1.20-1.0.0-SNAPSHOT.jar arclight_implementer PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.20-46.0.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20-46.0.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20-46.0.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20-46.0.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20-46.0.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.20-20230608.053357-srg.jar               |Minecraft                     |minecraft                     |1.20                    |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20-46.0.1-universal.jar                   |Forge                         |forge                         |46.0.1              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		architectury-9.1.10-forge.jar                     |Architectury                  |architectury                  |9.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		MTR-forge-1.20-3.2.2-hotfix-1.jar                 |Minecraft Transit Railway     |mtr                           |1.20-3.2.2-hotfix-1 |ERROR     |Manifest: NOSIGNATURE
		arclight-1.20-1.0.0-SNAPSHOT-0293741.jar          |Arclight Mod                  |arclight                      |1.20-1.0.0-SNAPSHOT-|COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 65a2d3c8-20e8-42c6-9763-70826fd66a3c
	FML: 46.0
	Forge: net.minecraftforge:46.0.1
```

**Comment by littlekan233** [comment]
最后降级到1.19.4了，已经解决了，1.20等修复吧
Finally downgraded to 1.19.4, it's fixed, 1.20 wait for the fixes
